version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: gunicorn myviews.wsgi:application --bind 0.0.0.0:8080
    command: python3 app.py
    volumes:
      - .:/riche
    ports:
      - 8001:8001
